sudo: false

language: node_js

node_js:
  - 'iojs'
  - '0.12'
  - '0.10'

before_script:
  - "npm install"

script:
  - "npm test"

after_script:
  - "npm test:browser"

env:
  global:
  - secure: QeYIabbwS7yaSYa8HQVE7jR7WaZwHRiMfYXxoGCHKVRYkmBWLGMAK+WqjOtH3GLgH56cgwxuv6ec1xM1RBBtCmnAyxumlTEe9h929gidAuqs8Mo3e4W7QLGOyICJHVD2Hgo3d3VM00KFOqLhZ3JvPfK/DPPRBM3J5fRUSW48tt8=
  - secure: OQxSapplFZEqhdbYGtM0QhW0KLCCGNiDp3zO0f6RQJ+JQwFM6A7EV5wtSJ1Xd3Szsbvx/Z3ZiENqqKaD62vTrqcMEjCoFA4cpt9opQvqcf88IaGG5MtUAmrrHplQR+8iBawrj/hA/RagmfvbnfG56fgWlpL+QYdEGQlGbuFBwzA=

